### ISSUE TITLE
Creation and update of `ReMapEnrich.Rproj`

### ISSUE THREAD

**Issue by benoitballester** [remap-cisreg/ReMapEnrich#2]
Can someone tells me how the `ReMapEnrich.Rproj` file is created ? 
Is it during build in Rstudio ?

**Comment by jvanheld** [comment]
In RStudio, when you create a project you are asked to indicate the directory in which it will be stored. RStudio then creates an Rproj file, which is a very small text files containing the RStudio options  of the project. 

The main interest is that you can then open the RProj file (by double-clicking on it) and this opens the project in RStudio , and positions you in the project-associated folder. 

This enables to manage several projects and open them in parallel while being always in the right folder. sDD

**Comment by benoitballester** [comment]
Dear @jvanheld thanks for the prompt reply. 
Does it have to be updated for each new build, or left as it is ?

**Comment by jvanheld** [comment]
The Rproj has not specially to be updated, it just contains a memory of the parameters that you specify with the "Project options" menu in RStudio. s
