### ISSUE TITLE
Example ReMapEnrich/man/enrichmentBarPlot.Rd

### ISSUE THREAD

**Issue by AllyssaM1** [remap-cisreg/ReMapEnrich#4]
Nous avons remarqué que l'exemple  ReMapEnrich/man/enrichmentBarPlot.Rd ne fonctionne pas.
```
data("enrichment_example", package = "ReMapEnrich")
enrichmentBarPlot(enrichment_example)
```

L'exemple renvoi ce message d'erreur:

> Error in enrichmentBarPlot(enrichment_example) : 
>   objet 'enrichment_example' introuvable

Cela fonctionne après modification de la variable enrichmentExample:
```
data("enrichment_example", package = "ReMapEnrich")
enrichmentBarPlot(enrichmentExample)
```

L'erreur semble commune au Dot, Bar et Volcano Plot.

**Comment by MartinMestdagh** [comment]
En effet des changements ont eu lieu sur les noms des variables.
Correction à effectuer:
`enrichmentBarPlot(enrichmentExample)`
au lieu de `enrichmentBarPlot(enrichment_example)`
merci pour votre retour.

**Comment by benoitballester** [comment]
Je viens de faire la modification, et le commit.
