### ISSUE TITLE
EnrichmentDotPlot error

### ISSUE THREAD

**Issue by AllyssaM1** [remap-cisreg/ReMapEnrich#5]
Le paramètre aRisk ne semble pas supporté par la fonction  
`enrichmentDotPlot(enrichmentExample,aRisk=0.05)`

et renvoi un message d'erreur:
> Error in graphics::par(defPar) : 
>   valeur spécifiée pour le paramètre graphique "pin" incorrect
> De plus : Warning messages:
> 1: In plot.window(...) : "aRisk" n'est pas un paramètre graphique
> 2: In plot.xy(xy, type, ...) : "aRisk" n'est pas un paramètre graphique
> 3: In axis(side = side, at = at, labels = labels, ...) :
>   "aRisk" n'est pas un paramètre graphique
> 4: In axis(side = side, at = at, labels = labels, ...) :
>   "aRisk" n'est pas un paramètre graphique
> 5: In box(...) : "aRisk" n'est pas un paramètre graphique
> 6: In title(...) : "aRisk" n'est pas un paramètre graphique
> 7: In graphics::symbols(x = mapped.peaks.ratio, y = 1:top, circles = (nb.overlaps -  :
>   "aRisk" n'est pas un paramètre graphique

**Comment by MartinMestdagh** [comment]
Bonjour,
en effet l'argument aRisk n'est pas présent dans la fonction enrichmentDotPlot.
Je dois modifier la vignette de cette fonction.
Merci pour votre message.

**Comment by benoitballester** [comment]
Merci Martin d'y jeter un oeil ;-) 
Nous avions bien avancé sur le RShiny, faut que te passes le lien pour que tu regardes (mais en off).

**Comment by AllyssaM1** [comment]
Merci pour le retour
