### ISSUE TITLE
Numbers of bars in enrichmentBarPlot

### ISSUE THREAD

**Issue by benoitballester** [remap-cisreg/ReMapEnrich#6]
The number of bars in enrichmentBarPlot does not correspond to the number given by top = X

For example : 
`enrichmentBarPlot(enrichment.df, top = 2)`

gives 3 bars. I would expect 2 bars, unless it is a feature which will have to be explained. ;-)

**Comment by MartinMestdagh** [comment]
in fact there was always one more bar on each plot.

**Comment by benoitballester** [comment]
Du coup on peux le corriger ?

**Comment by MartinMestdagh** [comment]
oui je viens de le faire, j'ai pull normalement...
![pullrequest](https://user-images.githubusercontent.com/45970232/60822577-001c2b80-a1a6-11e9-98ad-6a2b65b853c8.png)

**Comment by MartinMestdagh** [comment]
Est-ce que les changements ont bien eu lieu Benoît?
